language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
script:
  - pytest
  - make sphinx
  - flake8 --ignore=E402,F401,F811 RunRules ScanResources StoreResources TagResources TaskScheduler tests
before_deploy:
  - make sphinx
deploy:
  - provider: pages
    skip_cleanup: true
    local-dir: docs/build/html
    github-token: $GITHUB_TOKEN
    keep-history: true
    on:
      branch: master